[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[env]
SPOTIFY_CLIENT_ID = { reference = "SPOTIFY_CLIENT_ID" }
SPOTIFY_CLIENT_SECRET = { reference = "SPOTIFY_CLIENT_SECRET" }
SECRET_KEY = { reference = "SECRET_KEY" }
DATABASE_URL = { reference = "DATABASE_URL" }
ENVIRONMENT = "production"